<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "szag_carousel"
 *
 * Auto generated by Extension Builder 2016-06-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Salzgitter AG Carousel',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Markus Klinger',
	'author_email' => 'klinger@pierraa-design.de',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);